// The JavaScript handle on the Android background uploader.
//
// This module does not upload anything. It hands WorkManager a job id and a
// file path and then only ever asks what happened — because the upload has to
// keep running when this JavaScript context no longer exists, which is the
// whole point of stage 8A [DECIDE 1]. Anything this file did during an upload
// would stop the moment the app was killed.
//
// The native argument list is NOT compile-time checked. The module is
// registered by hand through a BaseReactPackage rather than generated by
// codegen, so the signatures here and in DayReelUploadModule.kt are kept in
// step by reading them. Changing one means changing the other.
//
// It is registered as a legacy module, not a TurboModule, and reaches JS
// through the interop binding — see DayReelUploadPackage.kt for the measurement
// that forced that. Under bridgeless React Native `global.__turboModuleProxy`
// does not exist (verified on device), so TurboModuleRegistry.get falls through
// to NativeModules, and both names below resolve through the same
// BridgelessNativeModuleProxy.

import {
  NativeModules,
  Platform,
  TurboModuleRegistry,
  type TurboModule,
} from 'react-native';

/** Mirrors WorkManager's WorkInfo.State, plus NONE for "never enqueued here". */
export type UploadWorkState =
  | 'NONE'
  | 'ENQUEUED'
  | 'RUNNING'
  | 'SUCCEEDED'
  | 'FAILED'
  | 'BLOCKED'
  | 'CANCELLED';

export interface UploadStatus {
  state: UploadWorkState;
  /** WorkManager's own notion of terminal. Absent when state is NONE. */
  finished?: boolean;
  uploadedParts: number;
  totalParts: number;
  /** 0..1. Comes from live progress while running, from output data after. */
  fraction: number;
  runAttemptCount: number;
  failureReason?: string;
}

// Extends TurboModule because that is the type TurboModuleRegistry.get is
// declared over, not because codegen consumes this file — it does not, and the
// Kotlin class is not a TurboModule. This interface is documentation with a
// compiler attached, and it is only as correct as the last person to read both.
interface DayReelUploadSpec extends TurboModule {
  startUpload(
    jobId: string,
    apiBaseUrl: string,
    filePath: string,
    debugPartDelayMs: number,
  ): Promise<string>;
  getUploadStatus(jobId: string): Promise<UploadStatus>;
  cancelUpload(jobId: string): Promise<boolean>;
}

/**
 * Resolve the module, tolerating its absence.
 *
 * It is Android-only and app-local, so on iOS — and in Jest, and in any build
 * where the package failed to register — it simply is not there. Returning null
 * rather than throwing at import time keeps that a runtime decision the caller
 * can act on, instead of a crash before the app renders.
 */
function resolve(): DayReelUploadSpec | null {
  if (Platform.OS !== 'android') {
    return null;
  }
  try {
    return (
      TurboModuleRegistry.get<DayReelUploadSpec>('DayReelUpload') ??
      (NativeModules.DayReelUpload as DayReelUploadSpec | undefined) ??
      null
    );
  } catch {
    return null;
  }
}

const nativeModule = resolve();

// Registration failing is silent by construction: `resolve` returns null, the
// caller falls back to the foreground uploader, and the app behaves exactly as
// it did before this module existed. That is precisely what happened for the
// whole of 8A's first implementation. On Android there is no legitimate reason
// for the module to be missing, so say so out loud.
if (__DEV__ && Platform.OS === 'android' && nativeModule === null) {
  console.warn(
    'DayReelUpload did not resolve. Uploads will run in the foreground and ' +
      'will NOT survive the app being killed. Check that the app was rebuilt ' +
      'after DayReelUploadPackage changed.',
  );
}

/** Whether background upload is available at all on this build and platform. */
export function isBackgroundUploadAvailable(): boolean {
  return nativeModule !== null;
}

function required(): DayReelUploadSpec {
  if (!nativeModule) {
    throw new Error(
      'DayReelUpload native module is unavailable; background upload is ' +
        'Android-only and requires the app to have been rebuilt after the ' +
        'module was added',
    );
  }
  return nativeModule;
}

/**
 * Hand an already-created job to WorkManager.
 *
 * `POST /jobs` happens in JavaScript; only the transfer is native. The worker
 * deliberately ignores the upload URLs that call returned and asks
 * `/upload-urls` for its own, so a fresh upload and a resumed one follow one
 * code path and no presigned URL is ever used after sitting in storage.
 *
 * Enqueueing is idempotent per job (WorkManager `KEEP`), so calling this again
 * for a job already in flight is a safe no-op rather than a second upload.
 *
 * `debugPartDelayMs` exists because at loopback speed a multi-part upload
 * finishes in well under a second, leaving no window in which to kill the app
 * and observe that it survived — [DECIDE 6]. It must be 0 outside deliberate
 * testing.
 */
export async function startBackgroundUpload(args: {
  jobId: string;
  apiBaseUrl: string;
  filePath: string;
  debugPartDelayMs?: number;
}): Promise<string> {
  return required().startUpload(
    args.jobId,
    args.apiBaseUrl,
    args.filePath,
    args.debugPartDelayMs ?? 0,
  );
}

/**
 * Ask WorkManager what it believes about this job.
 *
 * Polled rather than subscribed, deliberately. The upload's real state lives in
 * WorkManager and in S3; an event stream would create a third copy in
 * JavaScript that is wrong every time the app was not running to receive one.
 * Asking is always correct — being told is only correct while someone listens.
 */
export async function getBackgroundUploadStatus(
  jobId: string,
): Promise<UploadStatus> {
  return required().getUploadStatus(jobId);
}

/**
 * Stop the work.
 *
 * This cancels the transfer only. The multipart upload still exists in S3 and
 * is still accruing storage charges until it is completed or aborted — use
 * `DELETE /jobs/{id}/upload` for that. The two are separate on purpose: a user
 * cancelling on a train has not necessarily abandoned the upload.
 */
export async function cancelBackgroundUpload(jobId: string): Promise<boolean> {
  return required().cancelUpload(jobId);
}
