#!/usr/bin/env bash
#
# Proves the stage 8A resume path from curl, with no app.
#
# The claim under test is narrow and worth stating exactly: an upload can be
# interrupted with some parts on S3 and finished later, using URLs the server
# mints fresh, without the client having recorded a single ETag. Everything else
# here is a negative check on that claim.
#
#   ./scripts/verify-resume.sh
#   API=http://localhost:8080 ./scripts/verify-resume.sh
#
# TWO LOCAL FACTS THIS SCRIPT WORKS AROUND, BOTH LEARNED THE HARD WAY:
#
# 1. S3_PUBLIC_ENDPOINT is http://10.0.2.2:4566 — the Android emulator's alias
#    for the host loopback — and this machine cannot route to it. Rewriting the
#    URL's host would invalidate the signature, which is the entire point of
#    that setting. So the PUTs below use curl --connect-to: the signed Host
#    header stays 10.0.2.2 and only the TCP connection is redirected. The
#    signature is genuinely exercised, not sidestepped.
#
# 2. `curl --data-binary` defaults to Content-Type: application/x-www-form-
#    urlencoded, and LocalStack then tries to FORM-PARSE a 5 MiB part and
#    answers 413 Request Entity Too Large wrapped in a 500. Every PUT here sets
#    application/octet-stream. scripts/verify-presign.sh never hit this because
#    its payload is 29 bytes.
#
# Parts are 5 MiB minimum — S3 and LocalStack both enforce it on every part but
# the last — so the fixture has to exceed 5 MiB for any of this to be multipart
# at all.
#
# It has to be a REAL video, not random bytes, because the last check runs the
# pipeline on the resumed upload and validate rejects anything ffprobe cannot
# read. It is generated by ffmpeg inside a worker container — ffmpeg is a
# guaranteed dependency there and not one on the host — and is never committed.
set -uo pipefail

API="${API:-http://localhost:8080}"
CONTAINER="${CONTAINER:-dayreel-localstack}"
FFMPEG_CONTAINER="${FFMPEG_CONTAINER:-dayreel-worker-validate}"
BUCKET="${BUCKET:-dayreel-raw-videos}"

PART_SIZE=5242880

work="$(mktemp -d)"
trap 'rm -rf "$work";
      docker exec "$CONTAINER" rm -rf /tmp/verify-resume >/dev/null 2>&1;
      docker exec "$FFMPEG_CONTAINER" rm -f /tmp/verify-resume-clip.mp4 >/dev/null 2>&1' EXIT

pass=0; fail=0

check() {
  local name="$1" want="$2" got="$3"
  if [ "$got" = "$want" ]; then
    printf '  %-46s PASS (%s)\n' "$name" "$got"; pass=$((pass+1))
  else
    printf '  %-46s FAIL (want %s, got %s)\n' "$name" "$want" "$got"; fail=$((fail+1))
  fi
}

jqp() { python3 -c "import json,sys;d=json.load(sys.stdin);print($1)"; }

# create_job returns the raw POST /jobs response.
create_job() {
  curl -s -X POST "$API/jobs" -H 'Content-Type: application/json' \
    -d "{\"filename\":\"$1\",\"size_bytes\":$FIXTURE_SIZE,\"content_type\":\"video/mp4\"}"
}

# make_fixture writes an 8-second clip well over 5 MiB. The bitrate is forced
# high on purpose: at a sane bitrate an 8-second clip is under 5 MiB and the
# whole thing collapses to one part, which exercises nothing.
make_fixture() {
  docker exec "$FFMPEG_CONTAINER" ffmpeg -y -loglevel error \
    -f lavfi -i testsrc2=size=1920x1080:rate=30:duration=8 \
    -f lavfi -i sine=frequency=440:duration=8 \
    -c:v libx264 -preset ultrafast -b:v 12M -pix_fmt yuv420p \
    -c:a aac -b:a 128k -t 8 /tmp/verify-resume-clip.mp4
  docker cp "$FFMPEG_CONTAINER":/tmp/verify-resume-clip.mp4 "$work/clip.bin" >/dev/null
}

# put_part uploads a local part file through a presigned URL. See note 1 and 2.
put_part() {
  curl -s -o /dev/null -w '%{http_code}' -X PUT \
    -H 'Content-Type: application/octet-stream' \
    --connect-to 10.0.2.2:4566:127.0.0.1:4566 \
    --data-binary @"$2" "$1"
}

# put_part_container uploads without going through a presigned URL at all. Used
# to simulate parts that landed in a previous, now-dead process.
put_part_container() {
  docker exec "$CONTAINER" awslocal s3api upload-part --bucket "$BUCKET" \
    --key "$1" --upload-id "$2" --part-number "$3" --body "$4" >/dev/null
}

echo "stage 8A resume verification — api=$API"

make_fixture
FIXTURE_SIZE="$(wc -c < "$work/clip.bin" | tr -d ' ')"
EXPECT_PARTS=$(( (FIXTURE_SIZE + PART_SIZE - 1) / PART_SIZE ))
echo "  fixture: $FIXTURE_SIZE bytes -> $EXPECT_PARTS parts at ${PART_SIZE}B"
# Exactly three, because the checks below name part_aa/ab/ac directly and treat
# part 2 as the one gap. A four-part fixture would leave parts 4+ missing too
# and the "only the missing part" assertion would be measuring the wrong thing.
if [ "$EXPECT_PARTS" -ne 3 ]; then
  echo "  fixture is $EXPECT_PARTS parts; this script assumes 3. Adjust the bitrate." >&2
  exit 1
fi

split -b "$PART_SIZE" "$work/clip.bin" "$work/part_"
docker exec "$CONTAINER" mkdir -p /tmp/verify-resume
for f in "$work"/part_*; do docker cp "$f" "$CONTAINER":/tmp/verify-resume/ >/dev/null; done

# ── The upload plan ───────────────────────────────────────────────────────────
job_json="$(create_job clip.mp4)"
JOB="$(jqp 'd["job_id"]' <<<"$job_json")"
UPLOAD="$(jqp 'd["upload_id"]' <<<"$job_json")"
KEY="$JOB/clip.mp4"

check "POST /jobs returns $EXPECT_PARTS parts" "$EXPECT_PARTS" "$(jqp 'len(d["upload_urls"])' <<<"$job_json")"
check "presigned against the public endpoint" "10.0.2.2:4566" \
  "$(jqp '__import__("urllib.parse").parse.urlparse(d["upload_urls"][0]["url"]).netloc' <<<"$job_json")"

# ── The kill: parts land out of order, then the client disappears ─────────────
# Out of order on purpose. A killed client's parts are a SET, not a prefix, and
# a resume that assumes a contiguous prefix passes this only by luck.
put_part_container "$KEY" "$UPLOAD" 3 /tmp/verify-resume/part_ac
put_part_container "$KEY" "$UPLOAD" 1 /tmp/verify-resume/part_aa

# ── The invisibility demonstration ────────────────────────────────────────────
# Two listings of the same bucket disagree about whether ~7.7 MiB exists. This
# is why DECIDE 4 is a correctness requirement and not a cost one.
in_objects="$(docker exec "$CONTAINER" awslocal s3 ls "s3://$BUCKET/" --recursive | grep -c "$JOB")"
in_mpu="$(docker exec "$CONTAINER" awslocal s3api list-multipart-uploads --bucket "$BUCKET" \
  --query "length(Uploads[?Key=='$KEY'])" --output text)"
check "abandoned parts absent from s3 ls" 0 "$in_objects"
check "abandoned parts present in list-mpu" 1 "$in_mpu"

# ── The endpoint the stage exists for ─────────────────────────────────────────
resume="$(curl -s -X POST "$API/jobs/$JOB/upload-urls")"
check "resume lists the 2 parts S3 holds" "1,3" \
  "$(jqp '",".join(str(p["part_number"]) for p in sorted(d["uploaded_parts"], key=lambda p: p["part_number"]))' <<<"$resume")"
check "resume offers ONLY the missing part" "2" \
  "$(jqp '",".join(str(u["part_number"]) for u in d["upload_urls"])' <<<"$resume")"
check "re-issued url keeps the public host" "10.0.2.2:4566" \
  "$(jqp '__import__("urllib.parse").parse.urlparse(d["upload_urls"][0]["url"]).netloc' <<<"$resume")"
# The ETags must be S3's own. A client that never recorded one still gets them.
check "etags are S3's, quoted as S3 returns them" "True" \
  "$(jqp 'all(p["etag"].startswith(chr(34)) for p in d["uploaded_parts"])' <<<"$resume")"

resume_url="$(jqp 'd["upload_urls"][0]["url"]' <<<"$resume")"

# A re-issued URL must be a real signature, not merely a well-formed string.
# S3_SKIP_SIGNATURE_VALIDATION=0 in compose is what makes these rows mean
# anything; with it on, all four would pass trivially.
sig="$(python3 -c "import urllib.parse as u,sys;print(u.parse_qs(u.urlparse(sys.argv[1]).query)['X-Amz-Signature'][0])" "$resume_url")"
bad="$([ "${sig:0:1}" = "a" ] && echo "b${sig:1}" || echo "a${sig:1}")"
check "re-issued url rejects a corrupt signature" 403 "$(put_part "${resume_url/$sig/$bad}" "$work/part_ab")"
check "re-issued url rejects a rewritten host" 403 \
  "$(curl -s -o /dev/null -w '%{http_code}' -X PUT -H 'Content-Type: application/octet-stream' \
     --data-binary @"$work/part_ab" "${resume_url/10.0.2.2:4566/localhost:4566}")"
check "re-issued url rejects a tampered part no." 403 \
  "$(put_part "${resume_url/partNumber=2/partNumber=3}" "$work/part_ab")"
check "re-issued url accepts the real PUT" 200 "$(put_part "$resume_url" "$work/part_ab")"

check "resume is idempotent: nothing left missing" 0 \
  "$(curl -s -X POST "$API/jobs/$JOB/upload-urls" | jqp 'len(d["upload_urls"])')"

# ── Completion with no client-held state whatsoever ───────────────────────────
# No body at all. The server derives the part list, in order, with matching
# ETags, from ListParts. This is what makes "the client never persists an ETag"
# true rather than nearly true.
check "POST /complete with NO body" 200 \
  "$(curl -s -o /dev/null -w '%{http_code}' -X POST "$API/jobs/$JOB/complete")"
check "the assembled object is byte-exact" "$FIXTURE_SIZE" \
  "$(docker exec "$CONTAINER" awslocal s3api head-object --bucket "$BUCKET" --key "$KEY" \
     --query ContentLength --output text)"

# ── Error codes. The client's recovery differs per code, so a generic 500 or a
#    catch-all 400 would be worse than no code at all. ─────────────────────────
check "unknown job -> 404" 404 \
  "$(curl -s -o /dev/null -w '%{http_code}' -X POST "$API/jobs/00000000-0000-0000-0000-000000000000/upload-urls")"
check "completed job -> 409 ALREADY_COMPLETE" "409 ALREADY_COMPLETE" \
  "$(curl -s -w ' %{http_code}' -X POST "$API/jobs/$JOB/upload-urls" \
    | python3 -c "import json,sys;t=sys.stdin.read();b,c=t.rsplit(' ',1);print(c,json.loads(b)['code'])")"

# ── Abort, and what the client sees afterwards ────────────────────────────────
job2_json="$(create_job cancelled.mp4)"
JOB2="$(jqp 'd["job_id"]' <<<"$job2_json")"
put_part_container "$JOB2/cancelled.mp4" "$(jqp 'd["upload_id"]' <<<"$job2_json")" 1 /tmp/verify-resume/part_aa

check "DELETE /jobs/{id}/upload" 200 \
  "$(curl -s -o /dev/null -w '%{http_code}' -X DELETE "$API/jobs/$JOB2/upload")"
check "the parts are actually gone from S3" 0 \
  "$(docker exec "$CONTAINER" awslocal s3api list-multipart-uploads --bucket "$BUCKET" \
     --query "length(Uploads[?Key=='$JOB2/cancelled.mp4'])" --output text)"
check "abort twice is not an error" 200 \
  "$(curl -s -o /dev/null -w '%{http_code}' -X DELETE "$API/jobs/$JOB2/upload")"
# 410, not 500. Without a distinguishable code the client retries forever
# against an upload that no longer exists.
check "resume after abort -> 410 UPLOAD_GONE" "410 UPLOAD_GONE" \
  "$(curl -s -w ' %{http_code}' -X POST "$API/jobs/$JOB2/upload-urls" \
    | python3 -c "import json,sys;t=sys.stdin.read();b,c=t.rsplit(' ',1);print(c,json.loads(b)['code'])")"

# ── Truncation. S3 will assemble an object from a subset of its parts and
#    return 200, so a client that completes early gets a silently short video
#    that fails several stages away as an ffprobe error. ────────────────────────
job3_json="$(create_job partial.mp4)"
JOB3="$(jqp 'd["job_id"]' <<<"$job3_json")"
put_part_container "$JOB3/partial.mp4" "$(jqp 'd["upload_id"]' <<<"$job3_json")" 1 /tmp/verify-resume/part_aa
check "complete with 1 of 3 parts -> 409" "409 INCOMPLETE_UPLOAD" \
  "$(curl -s -w ' %{http_code}' -X POST "$API/jobs/$JOB3/complete" \
    | python3 -c "import json,sys;t=sys.stdin.read();b,c=t.rsplit(' ',1);print(c,json.loads(b)['code'])")"
check "a stale upload_id -> 409 UPLOAD_MISMATCH" "409 UPLOAD_MISMATCH" \
  "$(curl -s -w ' %{http_code}' -X POST "$API/jobs/$JOB3/complete" -H 'Content-Type: application/json' \
     -d '{"upload_id":"an-upload-id-from-some-other-job"}' \
    | python3 -c "import json,sys;t=sys.stdin.read();b,c=t.rsplit(' ',1);print(c,json.loads(b)['code'])")"
curl -s -o /dev/null -X DELETE "$API/jobs/$JOB3/upload"

# ── The pipeline must not be able to tell ─────────────────────────────────────
# A resumed upload is just an object. If this ever fails, resume is producing a
# file that differs from a fresh upload's, which every check above would miss.
status=""
for _ in $(seq 1 30); do
  status="$(curl -s "$API/jobs/$JOB" | jqp 'd["status"]')"
  [ "$status" = "completed" ] || [ "$status" = "failed" ] && break
  sleep 5
done
check "the pipeline ran on the resumed upload" "completed" "$status"
check "GET /jobs/{id}/reel" 200 "$(curl -s -o /dev/null -w '%{http_code}' "$API/jobs/$JOB/reel")"

echo
echo "pass=$pass fail=$fail"
echo
echo "NOT PROVEN HERE, and neither is provable in a session:"
echo "  - the lifecycle rule's effect. LocalStack accepts it, reads it back and"
echo "    never acts on it; see infra/localstack/init-aws.sh. Run"
echo "    scripts/abort-stale-uploads.sh to actually release what this left."
echo "  - ListParts paging. The loop exists and 3 parts never reach page two."
[ "$fail" -eq 0 ]
